### ISSUE TITLE
Fall 2024 Plans

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/Argos#213]
### Overview

Reid and Jack planning stuff we want to work on (timelines and priorities) for Fall 2024

### Stakeholders

Product Stakeholder: @CatherineKennedy
Software Stakeholder: @jr1221 @RChandler234 
Reference Users:

### User Story

As a software lead I wanna know what the freak we're doing

### Success Metrics

Are Papa Peyton and Daddy Dylan happy

### Rollout Plan

Will put timeline stuff here

### Out of Scope

visualizing cell data in the frontend (on the backburner)

### Background / Context

- [ ] #175 - to / (migration and code change)

- [ ] UI for responsive/ reactive epic
- [ ] Fault Page

- [x] simplify schema
- [x] Clean up codebase (naming, old scripts, unused stuff), archive existing repo and make a new one?
- [x] protobuf optimizations (numbers should be numbers, not strings; a plan for lists [ids for associated values]; new source of time) 
- [ ] show git version of repos on car from Argos
- [ ] dynamic rate limiting
- [ ] UI for sending can messages to the car
- [ ] D3 graph
- [x] Make charybdis not stupid (way to view raw database, easier to run, no errors!)

### Acceptance Criteria & Mock-ups

Add Priorities here:

### Tickets

 - [ ] #
 - [ ] #

**Comment by jr1221** [comment]
See #256
