### ISSUE TITLE
[Epic] - Spring 2025 Plans

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Argos#256]
### Overview

Plan for Spring 2025

### Stakeholders

@jr1221 @Peyton-McKee @bracyw 

### Success Metrics

Shit in the high priority is 100% done and tested.

### Rollout Plan

Each epic in the high/med priority is done and tested with mock data and real LV box, and merged.

### Out of Scope

TBD

### Background / Context

Plan for the Spring 2025 Semester leading up to competitions in early May and Mid July

### Tickets

**New Pages**
High Priority
- [x] #293 and related tickets

Medium Priority

- [ ] Scylla Config Page
 - [ ] #254
 - [x] #255
 - [x] #156 

Low Priority
- [ ] #137 

**Bug Fixes/optimizations/backend features**
High Priority
 - [ ] Argos Client Make use of all of Angular 18's optimization features
- [x] Charybdis 2.0 MVP
- [x] #177 
- [x] #203 
- [x] #253 
- [x] #244 
- [x] #232

Medium Priority
- [x] #182 

Low Priority:
- [x] #184 
- [ ] #229 
- [x] #214 
- [ ] #249

**Comment by jr1221** [comment]
Onboarding?
- Rust slideshow
 - Mini launchpad/starter ticket
 -

**Comment by RChandler234** [comment]
https://www.shuttle.dev/blog/2023/10/04/sql-in-rust

**Comment by jr1221** [comment]
See spring timeline: https://nerdocs.atlassian.net/wiki/spaces/NER/pages/707690497/Argos+Spring+2025+Development+Roadmap
